language: python
sudo: false
notifications:
  email: false
cache:
  directories:
  - "$HOME/.cache/pip"
python:
- '3.5'
install:
- pip install -U pip wheel
- pip install -r requirements.txt
script:
- nosetests -vv lemonway
